alias cat='bat'
alias vi='nvim'
alias ll='ls -lhrt'
alias glances='glances --disable-unicode'
alias find_3mo_dir='find . -maxdepth 1 -type d -mtime +89'
alias ls_by_size='du -h --max-depth=1 | sort -h'
alias glpretty='git log --pretty=format:"%h %ad | %s%d [%an]" --date=short'
alias mkdirtd='mkdir $(date +%y%m%d)'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias glgf='git log -p -- '
alias catcsv='mlr --icsv --opprint cat '
alias csvsum='mlr --icsv --opprint stats1 -a sum --fr ".*" '
